{{- if and .Values.customResources.policySet.create -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policy-documents.auth.sneaksanddata.com
spec:
  group: auth.sneaksanddata.com
  names:
    plural: policy-documents
    singular: policy-document
    kind: PolicyDocument
    shortNames:
      - pols
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schema:
                  type: string
                active:
                  type: boolean
                policies:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
{{end}}