{{- if and .Values.customResources.resourceDiscoveryDocument.create -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resource-discovery-documents.auth.sneaksanddata.com
spec:
  group: auth.sneaksanddata.com
  names:
    plural: resource-discovery-documents
    singular: resource-discovery-document
    kind: ResourceDiscoveryDocument
    shortNames:
      - resdoc
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                active:
                  type: boolean
                hostname:
                  type: string
                routes:
                  type: array
                  items:
                    type: object
                    properties:
                      routeTemplate:
                        type: string
                      resourceUid:
                        type: string
      subresources:
        status: {}
  scope: Namespaced
{{end}}